name: expensive_tracker_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  uuid: ^4.6.0
  hive: ^2.2.3
  intl: ^0.20.3
  path_provider: ^2.1.6
  cupertino_icons: ^1.0.9
  fl_chart: ^1.2.0
  google_fonts: ^8.2.1
  flutter_bloc: ^9.1.1
  equatable: ^2.1.0
  get_it: ^9.2.1
  dio: ^5.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.16.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

